In [ ]:
import sys
from pathlib import Path

def is_google_colab() -> bool:
    if "google.colab" in str(get_ipython()):
        return True
    return False

def clone_repository() -> None:
    !git clone https://github.com/featurestorebook/mlfs-book.git
    %cd mlfs-book

def install_dependencies() -> None:
    !pip install --upgrade uv
    !uv pip install --all-extras --system --requirement pyproject.toml

if is_google_colab():
    clone_repository()
    install_dependencies()
    root_dir = str(Path().absolute())
    print("Google Colab environment")
else:
    root_dir = Path().absolute()
    # Strip ~/notebooks/ccfraud from PYTHON_PATH if notebook started in one of these subdirectories
    if root_dir.parts[-1:] == ('airquality',):
        root_dir = Path(*root_dir.parts[:-1])
    if root_dir.parts[-1:] == ('notebooks',):
        root_dir = Path(*root_dir.parts[:-1])
    root_dir = str(root_dir) 
    print("Local environment")

# Add the root directory to the `PYTHONPATH` to use the `recsys` Python module from the notebook.
if root_dir not in sys.path:
    sys.path.append(root_dir)
print(f"Added the following directory to the PYTHONPATH: {root_dir}")
    
# Set the environment variables from the file <root_dir>/.env
# from mlfs import config
# settings = config.HopsworksSettings(_env_file=f"{root_dir}/.env")

Local environment
Added the following directory to the PYTHONPATH: /home/lukasfri/Repositories/github.com/GeorgesTohme/mlfs-book
HopsworksSettings initialized!

<span style="font-width:bold; font-size: 3rem; color:#333;">- Part 02: Daily Feature Pipeline for Air Quality (aqicn.org) and weather (openmeteo)</span>

## 🗒️ This notebook is divided into the following sections:
1. Download and Parse Data
2. Feature Group Insertion


__This notebook should be scheduled to run daily__

In the book, we use a GitHub Action stored here:
[.github/workflows/air-quality-daily.yml](https://github.com/featurestorebook/mlfs-book/blob/main/.github/workflows/air-quality-daily.yml)

However, you are free to use any Python Orchestration tool to schedule this program to run daily.

### <span style='color:#ff5f27'> 📝 Imports

In [2]:
import datetime
import time
import requests
import pandas as pd
import hopsworks
from mlfs.airquality import util
from mlfs import config
import json
import os
import warnings
warnings.filterwarnings("ignore")

## <span style='color:#ff5f27'> 🌍 Get the Sensor URL, Country, City, Street names from Hopsworks </span>

__Update the values in the cell below.__

__These should be the same values as in notebook 1 - the feature backfill notebook__

In [3]:
project = hopsworks.login(engine="python")
fs = project.get_feature_store() 
secrets = hopsworks.get_secrets_api()

# This line will fail if you have not registered the AQICN_API_KEY as a secret in Hopsworks
AQICN_API_KEY = secrets.get_secret("AQICN_API_KEY").value
location_str = secrets.get_secret("SENSOR_LOCATION_JSON").value
location = json.loads(location_str)

country=location['country']
city=location['city']
street=location['street']
aqicn_url=location['aqicn_url']
latitude=location['latitude']
longitude=location['longitude']

today = datetime.date.today()

location_str

2025-11-10 12:30:26,489 INFO: Initializing external client
2025-11-10 12:30:26,489 INFO: Base URL: https://c.app.hopsworks.ai:443

2025-11-10 12:30:27,710 INFO: Python Engine initialized.

Logged in to project, explore it here https://c.app.hopsworks.ai:443/p/1279130

'{"country": "sweden", "city": "Nora", "street": "Dalviksv\\u00e4gen", "aqicn_url": "https://api.waqi.info/feed/A249862", "latitude": "59.5313", "longitude": "15.0177"}'

### <span style="color:#ff5f27;"> 🔮 Get references to the Feature Groups </span>

In [4]:
# Retrieve feature groups
air_quality_fg = fs.get_feature_group(
    name='air_quality',
    version=1,
)
weather_fg = fs.get_feature_group(
    name='weather',
    version=1,
)

---

## <span style='color:#ff5f27'> 🌫 Retrieve Today's Air Quality data (PM2.5) from the AQI API</span>

In [5]:
import requests
import pandas as pd

aq_today_df = util.get_pm25(aqicn_url, country, city, street, today, AQICN_API_KEY)
aq_today_df

Fetching air quality data from URL: https://api.waqi.info/feed/A249862/?token=86c323fc1e3b1a8257f58250000cd9f67d692a8b
API response data: {'status': 'ok', 'data': {'aqi': 20, 'idx': -249862, 'attributions': [{'url': 'https://sensor.community/', 'name': 'Citizen Science project sensor.community', 'station': '70821'}, {'url': 'https://waqi.info/', 'name': 'World Air Quality Index Project'}], 'city': {'geo': [59.53225975484, 15.01603871584], 'name': 'Dalviksvägen', 'url': 'https://aqicn.org/station/@249862', 'location': 'Rosenhäll, Fridhem, Nora, Nora kommun, Örebro County, 71333, Sweden'}, 'dominentpol': 'pm25', 'iaqi': {'pm10': {'v': 6}, 'pm25': {'v': 20}}, 'time': {'s': '2025-11-10 13:27:40', 'tz': '+02:00', 'v': 1762774060, 'iso': '2025-11-10T11:27:40Z'}}}

,pm25,country,city,street,date,url
0,20.0,sweden,Nora,Dalviksvägen,2025-11-10,https://api.waqi.info/feed/A249862

In [6]:
aq_today_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   pm25     1 non-null      float32
 1   country  1 non-null      object
 2   city     1 non-null      object
 3   street   1 non-null      object
 4   date     1 non-null      datetime64[ns]
 5   url      1 non-null      object
dtypes: datetime64[ns](1), float32(1), object(4)
memory usage: 176.0+ bytes

## <span style='color:#ff5f27'> 🌦 Get Weather Forecast data</span>

In [7]:
hourly_df = util.get_hourly_weather_forecast(city, latitude, longitude)
hourly_df = hourly_df.set_index('date')

# We will only make 1 daily prediction, so we will replace the hourly forecasts with a single daily forecast
# We only want the daily weather data, so only get weather at 12:00
daily_df = hourly_df.between_time('11:59', '12:01')
daily_df = daily_df.reset_index()
daily_df['date'] = pd.to_datetime(daily_df['date']).dt.date
daily_df['date'] = pd.to_datetime(daily_df['date'])
daily_df['city'] = city
daily_df

Coordinates 59.5°N 15.0°E
Elevation 149.0 m asl
Timezone None None
Timezone difference to GMT+0 0 s

,date,temperature_2m_mean,precipitation_sum,wind_speed_10m_max,wind_direction_10m_dominant,city
0,2025-11-10,5.40,0.0,7.862518,105.945465,Nora
1,2025-11-11,6.30,0.0,4.802999,167.005386,Nora
2,2025-11-12,7.75,1.2,23.732710,189.605133,Nora
3,2025-11-13,5.25,0.0,21.407139,289.653900,Nora
4,2025-11-14,2.25,0.0,24.464113,302.988525,Nora
5,2025-11-15,2.95,0.0,12.240000,270.000000,Nora
6,2025-11-16,4.20,0.0,15.629971,298.926331,Nora

In [8]:
daily_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   date                         7 non-null      datetime64[ns]
 1   temperature_2m_mean          7 non-null      float32
 2   precipitation_sum            7 non-null      float32
 3   wind_speed_10m_max           7 non-null      float32
 4   wind_direction_10m_dominant  7 non-null      float32
 5   city                         7 non-null      object
dtypes: datetime64[ns](1), float32(4), object(1)
memory usage: 356.0+ bytes

## <span style="color:#ff5f27;">⬆️ Uploading new data to the Feature Store</span>

In [9]:
# Insert new data
air_quality_fg.insert(aq_today_df)

2025-11-10 12:30:31,983 INFO: 	1 expectation(s) included in expectation_suite.
Validation succeeded.
Validation Report saved successfully, explore a summary at https://c.app.hopsworks.ai:443/p/1279130/fs/1265739/fg/1595960

Uploading Dataframe: 100.00% |██████████| Rows 1/1 | Elapsed Time: 00:01 | Remaining Time: 00:00

Launching job: air_quality_1_offline_fg_materialization
Job started successfully, you can follow the progress at
https://c.app.hopsworks.ai:443/p/1279130/jobs/named/air_quality_1_offline_fg_materialization/executions

(Job('air_quality_1_offline_fg_materialization', 'SPARK'),
 {
   "success": true,
   "results": [
     {
       "success": true,
       "expectation_config": {
         "expectation_type": "expect_column_min_to_be_between",
         "kwargs": {
           "column": "pm25",
           "min_value": -0.1,
           "max_value": 500.0,
           "strict_min": true
         },
         "meta": {
           "expectationId": 733217
         }
       },
       "result": {
         "observed_value": 20.0,
         "element_count": 1,
         "missing_count": null,
         "missing_percent": null
       },
       "meta": {
         "ingestionResult": "INGESTED",
         "validationTime": "2025-11-10T11:30:31.000983Z"
       },
       "exception_info": {
         "raised_exception": false,
         "exception_message": null,
         "exception_traceback": null
       }
     }
   ],
   "evaluation_parameters": {},
   "statistics": {
     "evaluated_expectations": 1,
     "successful_expectations": 1,
     "unsuccessful_expectations": 0,
     "success_percent": 100.0
   },
   "meta": {
     "great_expectations_version": "0.18.12",
     "expectation_suite_name": "aq_expectation_suite",
     "run_id": {
       "run_name": null,
       "run_time": "2025-11-10T12:30:31.983413+01:00"
     },
     "batch_kwargs": {
       "ge_batch_id": "aaab9ec8-be28-11f0-b951-581122c172fc"
     },
     "batch_markers": {},
     "batch_parameters": {},
     "validation_time": "20251110T113031.983361Z",
     "expectation_suite_meta": {
       "great_expectations_version": "0.18.12"
     }
   }
 })

In [10]:
# Insert new data
weather_fg.insert(daily_df, wait=True)

2025-11-10 12:30:45,136 INFO: 	2 expectation(s) included in expectation_suite.
Validation succeeded.
Validation Report saved successfully, explore a summary at https://c.app.hopsworks.ai:443/p/1279130/fs/1265739/fg/1595961

Uploading Dataframe: 100.00% |██████████| Rows 7/7 | Elapsed Time: 00:00 | Remaining Time: 00:00

Launching job: weather_1_offline_fg_materialization
Job started successfully, you can follow the progress at
https://c.app.hopsworks.ai:443/p/1279130/jobs/named/weather_1_offline_fg_materialization/executions
2025-11-10 12:31:00,949 INFO: Waiting for execution to finish. Current state: SUBMITTED. Final status: UNDEFINED
2025-11-10 12:31:07,262 INFO: Waiting for execution to finish. Current state: RUNNING. Final status: UNDEFINED
2025-11-10 12:32:39,068 INFO: Waiting for execution to finish. Current state: AGGREGATING_LOGS. Final status: SUCCEEDED
2025-11-10 12:32:39,250 INFO: Waiting for log aggregation to finish.
2025-11-10 12:32:47,802 INFO: Execution finished successfully.

(Job('weather_1_offline_fg_materialization', 'SPARK'),
 {
   "success": true,
   "results": [
     {
       "success": true,
       "expectation_config": {
         "expectation_type": "expect_column_min_to_be_between",
         "kwargs": {
           "column": "wind_speed_10m_max",
           "min_value": -0.1,
           "max_value": 1000.0,
           "strict_min": true
         },
         "meta": {
           "expectationId": 733219
         }
       },
       "result": {
         "observed_value": 4.802999019622803,
         "element_count": 7,
         "missing_count": null,
         "missing_percent": null
       },
       "meta": {
         "ingestionResult": "INGESTED",
         "validationTime": "2025-11-10T11:30:45.000136Z"
       },
       "exception_info": {
         "raised_exception": false,
         "exception_message": null,
         "exception_traceback": null
       }
     },
     {
       "success": true,
       "expectation_config": {
         "expectation_type": "expect_column_min_to_be_between",
         "kwargs": {
           "column": "precipitation_sum",
           "min_value": -0.1,
           "max_value": 1000.0,
           "strict_min": true
         },
         "meta": {
           "expectationId": 733218
         }
       },
       "result": {
         "observed_value": 0.0,
         "element_count": 7,
         "missing_count": null,
         "missing_percent": null
       },
       "meta": {
         "ingestionResult": "INGESTED",
         "validationTime": "2025-11-10T11:30:45.000136Z"
       },
       "exception_info": {
         "raised_exception": false,
         "exception_message": null,
         "exception_traceback": null
       }
     }
   ],
   "evaluation_parameters": {},
   "statistics": {
     "evaluated_expectations": 2,
     "successful_expectations": 2,
     "unsuccessful_expectations": 0,
     "success_percent": 100.0
   },
   "meta": {
     "great_expectations_version": "0.18.12",
     "expectation_suite_name": "weather_expectation_suite",
     "run_id": {
       "run_name": null,
       "run_time": "2025-11-10T12:30:45.136497+01:00"
     },
     "batch_kwargs": {
       "ge_batch_id": "b282a2d6-be28-11f0-b951-581122c172fc"
     },
     "batch_markers": {},
     "batch_parameters": {},
     "validation_time": "20251110T113045.136449Z",
     "expectation_suite_meta": {
       "great_expectations_version": "0.18.12"
     }
   }
 })

## <span style="color:#ff5f27;">⏭️ **Next:** Part 03: Training Pipeline
 </span> 

In the following notebook you will read from a feature group and create training dataset within the feature store